sonar.projectKey=Notes-app
sonar.projectName=Notes-app
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.login=sqp_91f941f75a23de926c76d93233e31fcbfc36655e

sonar.modules=backend,frontend

#backend
backend.sonar.projectName=Backend
backend.sonar.sources=src
backend.sonar.tests=src/tests
backend.sonar.test.inclusions=src/tests/**/*.test.js,src/tests/**/*.spec.js
backend.sonar.javascript.lcov.reportPaths=coverage/lcov.info
backend.sonar.coverage.exclusions=src/server.js,src/app.js
backend.sonar.cpd.exclusions=src/tests/**
backend.sonar.exclusions=node_modules/**,coverage/**,generated/**,prisma/migrations/**,prisma/generated/**

#frontend
frontend.sonar.projectName=Frontend
frontend.sonar.sources=src
frontend.sonar.tests=src/tests
frontend.sonar.test.inclusions=src/tests/**/*.test.js,src/tests/**/*.test.jsx
frontend.sonar.javascript.lcov.reportPaths=coverage/lcov.info
frontend.sonar.exclusions=node_modules/**,coverage/**,dist/**