sonar.projectKey=Notes-app
sonar.projectName=Notes-app
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.login=sqp_91f941f75a23de926c76d93233e31fcbfc36655e

sonar.sources=src
sonar.tests=src/tests

sonar.sourceEncoding=UTF-8


sonar.javascript.lcov.reportPaths=coverage/lcov.info


sonar.test.inclusions=src/tests/**/*.test.js,src/tests/**/*.spec.js

sonar.coverage.exclusions=src/server.js,src/app.js

sonar.cpd.exclusions=src/tests/**

sonar.exclusions=node_modules/**,coverage/**,generated/**,prisma/migrations/**,prisma/generated/**